{% set name = "pyload-ng" %}
{% set version = "0.5.0b3.dev19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyload-ng-{{ version }}.tar.gz
  sha256: 65f5ec74671d085310cd0bc3ecabef2d60d87f8c381ab8fe878accc461bea8d2

build:
  entry_points:
    - pyload = pyload.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - bitmath >=1.3
    - cheroot >=8.4
    - cryptography~=36.0
    - filetype >=1.0
    - flask >=2.0
    - flask-babel =1.0
    - flask-caching >=1.9
    - flask-compress =1.8
    - flask-session >=0.3
    - flask-themes2 >=1.0
    - js2py >=0.7
    - pycurl >=7.43
    - python >=3.6
    - semver >=2.10
    - setuptools >=38.3

test:
  imports:
    - pyload
  commands:
    - pip check
    - pyload --help
  requires:
    - pip

about:
  home: https://pyload.net
  summary: The free and open-source Download Manager written in pure Python
  license: AGPL-3.0-or-later
  license_file: LICENSE.md
  dev_url: https://github.com/pyload/pyload
  doc_url: https://github.com/pyload/pyload/wiki

extra:
  recipe-maintainers:
    - HeavyTony2
